export const mockApiData = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    company: "ABC Inc",
    jobTitle: "Software Engineer",
    address: "123 Main St",
    city: "Techville",
    zipCode: "10001",
    country: "Futuria",
    contactDetails: [
      { type: "Email", info: "john@example.com" },
      { type: "Phone", info: "234 567 890" },
    ],
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    company: "XYZ Corp",
    jobTitle: "Product Manager",
    address: "456 Elm St",
    city: "Innovatown",
    zipCode: "20002",
    country: "Idealand",
    contactDetails: [
      { type: "Email", info: "jane@example.com" },
      { type: "Phone", info: "345 678 901" },
    ],
  },
  {
    id: 10,
    firstName: "Max",
    lastName: "Power",
    company: "DynaTech",
    jobTitle: "Team Lead",
    address: "987 New Horizons",
    city: "Explora",
    zipCode: "30003",
    country: "Discovery",
    contactDetails: [
      { type: "Email", info: "max@dynatech.com" },
      { type: "Phone", info: "800 123 456" },
    ],
  },
  {
    id: 11,
    firstName: "Luna",
    lastName: "Light",
    company: "MoonCorp",
    jobTitle: "CEO",
    address: "111 Crescent Lane",
    city: "Lunar City",
    zipCode: "40004",
    country: "Moonland",
    contactDetails: [
      { type: "Email", info: "luna@mooncorp.com" },
      { type: "Phone", info: "900 234 567" },
    ],
  },
  {
    id: 12,
    firstName: "Orion",
    lastName: "Star",
    company: "Galactic Innovations",
    jobTitle: "Research Scientist",
    address: "404 Starlight Avenue",
    city: "Cosmos",
    zipCode: "50005",
    country: "Universe",
    contactDetails: [
      { type: "Email", info: "orion@galacticinnovations.com" },
      { type: "Phone", info: "910 345 678" },
    ],
  },
  {
    id: 13,
    firstName: "Aurora",
    lastName: "Borealis",
    company: "Polar Lights Ltd.",
    jobTitle: "Creative Director",
    address: "321 Aurora Street",
    city: "North Pole",
    zipCode: "60006",
    country: "Arctica",
    contactDetails: [
      { type: "Email", info: "aurora@polarlights.com" },
      { type: "Phone", info: "920 456 789" },
    ],
  },
  {
    id: 14,
    firstName: "Leo",
    lastName: "Pride",
    company: "JungleTech",
    jobTitle: "Operations Manager",
    address: "567 Savanna Road",
    city: "Wildlands",
    zipCode: "70007",
    country: "Naturea",
    contactDetails: [
      { type: "Email", info: "leo@jungletech.com" },
      { type: "Phone", info: "930 567 890" },
    ],
  },
  {
    id: 15,
    firstName: "Cleo",
    lastName: "Nile",
    company: "PharaohTech",
    jobTitle: "Architect",
    address: "789 Pyramid Plaza",
    city: "Sphinx City",
    zipCode: "80008",
    country: "Egyptia",
    contactDetails: [
      { type: "Email", info: "cleo@pharahtech.com" },
      { type: "Phone", info: "940 678 901" },
    ],
  },
  {
    id: 16,
    firstName: "Terra",
    lastName: "Gaia",
    company: "EcoSolutions",
    jobTitle: "Environmental Engineer",
    address: "101 Mother Earth Ave",
    city: "Gaia",
    zipCode: "90009",
    country: "Globus",
    contactDetails: [
      { type: "Email", info: "terra@ecosolutions.com" },
      { type: "Phone", info: "950 789 012" },
    ],
  },
  {
    id: 17,
    firstName: "Nova",
    lastName: "Lumina",
    company: "Starlight Enterprises",
    jobTitle: "CEO",
    address: "202 Lightyear Blvd",
    city: "Nebula",
    zipCode: "100010",
    country: "Galaxia",
    contactDetails: [
      { type: "Email", info: "nova@starlight.com" },
      { type: "Phone", info: "960 890 123" },
    ],
  },
  {
    id: 18,
    firstName: "Zephyr",
    lastName: "Breeze",
    company: "WindPower Inc.",
    jobTitle: "Renewable Energy Specialist",
    address: "303 Highwind Street",
    city: "Aeolus",
    zipCode: "110011",
    country: "Atmos",
    contactDetails: [
      { type: "Email", info: "zephyr@windpower.com" },
      { type: "Phone", info: "970 901 234" },
    ],
  },
  {
    id: 19,
    firstName: "Atlas",
    lastName: "Worldview",
    company: "Global Mapping Solutions",
    jobTitle: "Cartographer",
    address: "404 Explore Way",
    city: "Mariner",
    zipCode: "120012",
    country: "Terra",
    contactDetails: [
      { type: "Email", info: "atlas@globalmapping.com" },
      { type: "Phone", info: "980 012 345" },
    ],
  },
];

export const authorizedMockUsers = [
  {
    email: "admin@admin.com",
    password: "password",
    user: {
      firstName: "John",
      lastName: "Doe",
      email: "admin@admin.com",
      role: "admin",
      token: "adminToken123456",
    },
  },
  {
    email: "user@user.com",
    password: "password",
    user: {
      firstName: "Jane",
      lastName: "Smith",
      email: "user@example.com",
      role: "user",
      token: "userToken123456",
    },
  },
];
